import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="h-16 flex items-center mx-auto container">
          <div className="text-2xl tracking-widest font-light">PIXEL</div>
        </nav>
        {children}
      </body>
    </html>
  );
}
